session_name: amber
start_directory: ${HOME}/Projects/amber
windows:

- window_name: frontend
  # layout: main-horizontal
  layout: tiled
  # layout: 9f9a,184x49,0,0[184x36,0,0,2,184x12,0,37,3]
  start_directory: ${HOME}/Projects/amber/frontend-angular-workspace
  options:
    # main-pane-height: 38
    automatic-rename: 'off'
  panes:
  - shell_command: null
    focus: 'true'
  - shell_command:
    - ./build_core.sh
  - shell_command:
    - sleep 5
    - ./serve_end_user.sh
  - shell_command:
    - sleep 5
    - ./serve_administration.sh
  focus: 'true'

- window_name: backend
  start_directory: ${HOME}/Projects/amber/backend-golang
  layout: main-horizontal
  # layout: 9f9a,184x49,0,0[184x36,0,0,2,184x12,0,37,3]
  options:
    main-pane-height: 38
    automatic-rename: 'off'
  panes:
  - shell_command: go run .
    focus: 'true'
  - shell_command: null
  - shell_command: null

- window_name: database
  start_directory: ${HOME}/Projects/amber/database-provisioning
  layout: main-horizontal
  options:
    main-pane-height: 38
    automatic-rename: 'off'
  panes:
  - shell_command: nvim -S
    focus: 'true'
  - shell_command: null
  - shell_command: null

- window_name: other
  start_directory: ${HOME}/Projects/amber
  layout: main-horizontal
  options:
    main-pane-height: 38
    automatic-rename: 'off'
  panes:
  - shell_command: null
    focus: 'true'
  - shell_command: null
  - shell_command: null
  # - shell_command:
  #   - clear

