// <auto-generated />
using System;
using DataProvisioningService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataProvisioningService.Migrations
{
    [DbContext(typeof(AmberSystemDbContext))]
    [Migration("20210123140031_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DataProvisioningService.Models.Base", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2021, 1, 23, 21, 0, 31, 579, DateTimeKind.Local).AddTicks(759));

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2021, 1, 23, 21, 0, 31, 582, DateTimeKind.Local).AddTicks(7247));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("Base");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Base");
                });

            modelBuilder.Entity("DataProvisioningService.Models.PresetValue", b =>
                {
                    b.HasBaseType("DataProvisioningService.Models.Base");

                    b.Property<string>("Language")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("vi");

                    b.Property<string>("ModuleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("PresetValue");
                });

            modelBuilder.Entity("DataProvisioningService.Models.StaticValue", b =>
                {
                    b.HasBaseType("DataProvisioningService.Models.Base");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Default")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT")
                        .HasColumnName("StaticValue_Language");

                    b.Property<string>("ModuleName")
                        .HasColumnType("TEXT")
                        .HasColumnName("StaticValue_ModuleName");

                    b.Property<string>("Placeholder")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("StaticValue");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Content = "Home",
                            Key = "home",
                            Language = "en",
                            ModuleName = "end_user_view.header.buttons",
                            Reference = "~/Home"
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Content = "About Us",
                            Key = "about_us",
                            Language = "en",
                            ModuleName = "end_user_view.header.buttons",
                            Reference = "~/AboutUs"
                        },
                        new
                        {
                            Id = 3,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Content = "For Sale",
                            Key = "for_sale",
                            Language = "en",
                            ModuleName = "end_user_view.header.buttons",
                            Reference = "~/ForSale"
                        },
                        new
                        {
                            Id = 4,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Content = "For Rent",
                            Key = "for_rent",
                            Language = "en",
                            ModuleName = "end_user_view.header.buttons",
                            Reference = "~/ForRent"
                        },
                        new
                        {
                            Id = 5,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Content = "Services",
                            Key = "services",
                            Language = "en",
                            ModuleName = "end_user_view.header.buttons",
                            Reference = "~/Services"
                        },
                        new
                        {
                            Id = 6,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Content = "Trang Chủ",
                            Key = "home",
                            Language = "vi",
                            ModuleName = "end_user_view.header.buttons",
                            Reference = "~/Home"
                        },
                        new
                        {
                            Id = 7,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Content = "Thông Tin",
                            Key = "about_us",
                            Language = "vi",
                            ModuleName = "end_user_view.header.buttons",
                            Reference = "~/AboutUs"
                        },
                        new
                        {
                            Id = 8,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Content = "Đang Bán",
                            Key = "for_sale",
                            Language = "vi",
                            ModuleName = "end_user_view.header.buttons",
                            Reference = "~/ForSale"
                        },
                        new
                        {
                            Id = 9,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Content = "Cho Thuê",
                            Key = "for_rent",
                            Language = "vi",
                            ModuleName = "end_user_view.header.buttons",
                            Reference = "~/ForRent"
                        },
                        new
                        {
                            Id = 10,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Content = "Dịch Vụ",
                            Key = "services",
                            Language = "vi",
                            ModuleName = "end_user_view.header.buttons",
                            Reference = "~/Services"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
