// <auto-generated />
using System;
using DataProvisioningService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataProvisioningService.Migrations
{
    [DbContext(typeof(AmberSystemDbContext))]
    [Migration("20210120033018_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DataProvisioningService.Models.Base", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2021, 1, 20, 10, 30, 18, 13, DateTimeKind.Local).AddTicks(5633));

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2021, 1, 20, 10, 30, 18, 17, DateTimeKind.Local).AddTicks(1451));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("Base");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Base");
                });

            modelBuilder.Entity("DataProvisioningService.Models.PresetValue", b =>
                {
                    b.HasBaseType("DataProvisioningService.Models.Base");

                    b.Property<string>("Language")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("vi");

                    b.Property<string>("ModuleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("PresetValue");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Language = "en",
                            ModuleName = "end_user_view.navbar_buttons.label.home",
                            Text = "Homepage"
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Language = "vi",
                            ModuleName = "end_user_view.navbar_buttons.label.home",
                            Text = "Trang chủ"
                        },
                        new
                        {
                            Id = 3,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Language = "en",
                            ModuleName = "end_user_view.navbar_buttons.label.about_us",
                            Text = "About us"
                        },
                        new
                        {
                            Id = 4,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Language = "vi",
                            ModuleName = "end_user_view.navbar_buttons.label.about_us",
                            Text = "Giới thiệu"
                        },
                        new
                        {
                            Id = 5,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Language = "en",
                            ModuleName = "end_user_view.navbar_buttons.label.for_sale",
                            Text = "Đang bán"
                        },
                        new
                        {
                            Id = 6,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Language = "vi",
                            ModuleName = "end_user_view.navbar_buttons.label.for_sale",
                            Text = "For sale"
                        },
                        new
                        {
                            Id = 7,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Language = "en",
                            ModuleName = "end_user_view.navbar_buttons.label.for_rent",
                            Text = "Cho thuê"
                        },
                        new
                        {
                            Id = 8,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Language = "vi",
                            ModuleName = "end_user_view.navbar_buttons.label.for_rent",
                            Text = "For rent"
                        },
                        new
                        {
                            Id = 9,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Language = "en",
                            ModuleName = "end_user_view.navbar_buttons.label.services",
                            Text = "Services"
                        },
                        new
                        {
                            Id = 10,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Language = "vi",
                            ModuleName = "end_user_view.navbar_buttons.label.services",
                            Text = "Các dịch vụ"
                        },
                        new
                        {
                            Id = 11,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Language = "en",
                            ModuleName = "end_user_view.navbar_right_button.label.contract_checking",
                            Text = "Check contract"
                        },
                        new
                        {
                            Id = 12,
                            CreatorId = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifierId = 0,
                            Visibility = 0,
                            Language = "vi",
                            ModuleName = "end_user_view.navbar_right_button.label.contract_checking",
                            Text = "Kiểm tra hợp đồng"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
