# https://taskfile.dev

version: '3'

tasks:

  up:
    cmds:
      - sudo docker-compose up -d
    silent: true

  assure:
    cmds:
      - ./caddy/assure_local_dns.sh
    silent: true

  up-backend:
    cmds:
      - sudo docker-compose up -d amber-backend
