# https://taskfile.dev

version: '3'

tasks:

  serve:
    cmds:
      - go run .
    silent: true

  build-docker-image:
    cmds:
      - sudo docker image build
        -t thanhnguyen2187/amber-backend
        .
  
  push-docker-image:
    deps:
      - build-docker-image
    cmds:
      - sudo docker push
        thanhnguyen2187/amber-backend:latest
