# https://taskfile.dev

version: '3'

tasks:
  build-core:
    cmds:
      - ng build
        --project amber-core

  build-core-watch:
    cmds:
      - ng build
        --project amber-core
        --watch

  # admin
  serve-admin:
    cmds:
      - ng serve
        --port 4200
        --project end-user
        --public-host amber.dev

  build-admin:
    env:
      NODE_ENV: production
    cmds:
      - ng build
        --project administration

  build-admin-tmp:
    env:
      NODE_ENV: production
    cmds:
      - ng build
        --project administration
        --output-path /tmp/amber-admin

  # end-user
  serve-end-user:
    cmds:
      - ng serve
        --port 4210
        --project administration
        --public admin.amber.dev
  
  build-end-user:
    env:
      NODE_ENV: production
    cmds:
      - ng build
        --project end-user

  build-end-user-tmp:
    env:
      NODE_ENV: production
    cmds:
      - ng build
        --project end-user
        --output-path /tmp/amber

  build-docker-image:
    # deps:
    #   - build-end-user-tmp
    #   - build-admin-tmp
    cmds:
      - sudo docker image build
        -t thanhnguyen2187/amber-frontend
        .

  push-docker-image:
    deps:
      - build-docker-image
    cmds:
      - sudo docker push thanhnguyen2187/amber-frontend:latest

  push-end-user-docker:
    deps:
      - build-end-user
    cmds:
      - rsync -vaR ./dist/end-user/ thanh@184.164.94.7:/tmp/amber

  deploy-admin:
    deps:
      - build-admin
    cmds:
      - rsync -vaR dist/administration/ thanh@184.164.94.7:/tmp/amber-admin
